appPrefix: tensorflow-distributed

MultiWorkerMirroredStrategy:
  replicas: 3
  nproc_per_node: 1
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: In
                values:
                  - "1"
                  - "2"
                  - "4"
                  - "8"
                  - "16"
                  
imageCredentials:
  registry: nvcr.io
  username: $oauthtoken
  password: "api-key"
  email: "user@nvidia.com"

baseImage:
  repository: registry.local:31500/distributed/tensorflow
  pullPolicy: Always
  tag: "v0.1.0"
  imagePullSecrets:
    - ngc-secret