{{- $image_version := "" }}
{{- $namespace := "" }}
{{- $appPrefix := "" }}
{{- $jobName := "" }}
{{- $i := "" }}
{{- $current := "" }}
{{- $affinity := "" }}
{{- $resources := "" }}
{{- $args := ""}}
{{- $myList := list }}
{{- $start := 0 }}
{{- $nproc_per_node := 1 }}

{{- $nproc_per_node := .Values.MultiWorkerMirroredStrategy.nproc_per_node | int  }}
{{- $image_version = printf "%s:%s" .Values.baseImage.repository .Values.baseImage.tag }}
{{- $namespace = .Release.Namespace | toString }}
{{- $appPrefix = .Values.appPrefix | toString }}
{{- $stop := .Values.MultiWorkerMirroredStrategy.replicas | int }}

{{- with .Values.MultiWorkerMirroredStrategy.affinity }}
    {{- $affinity = toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.MultiWorkerMirroredStrategy.resources }}
    {{- $resources = toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.MultiWorkerMirroredStrategy.args }}
    {{- $args = toYaml . | nindent 12 }}
{{- end }}

{{- range untilStep $start $stop 1 }}
  {{- $i = . | toString }}
  {{- $jobName = print $appPrefix "-" $i }}
  {{- $current = print $jobName "." $appPrefix "." $namespace ".svc.cluster.local:5005" | quote }}
  {{- $myList = append $myList $current }}
{{- end}}

{{- range untilStep $start $stop 1 }}
  {{- $i = . | toString }}
  {{- $jobName = print $appPrefix "-" $i }}
  {{- $current = print $jobName "." $appPrefix "." $namespace ".svc.cluster.local:5005" | quote }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $appPrefix }}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    metadata:
      labels: 
        app: {{ $appPrefix }}
    spec:
      affinity: 
    {{ $affinity }}
      imagePullSecrets:
        - name: ngc-secret
      subdomain: {{ $appPrefix }}
      hostname: {{ $jobName }}
      restartPolicy: Never
      containers: 
        - name: {{ $jobName }}
          image: {{ $image_version }}
          imagePullPolicy: Always
          resources:
        {{- $resources }}
          ports:
            - name: workers
              containerPort: 5005 
          args:
        {{ $args }}
          env:
            - name: TF_CONFIG
              value: '{"cluster": {"worker": [{{ join "," $myList }}]}, "task": {"index": {{ $i }}, "type": "worker"}}'
            - name: APP_NAME
              value: "{{ $appPrefix }}"
            - name: NUM_GPUS
              value: "{{ $nproc_per_node }}"
            - name: NCCL_DEBUG
              value: WARN
            - name: AUTOGRAPH_VERBOSITY
              value: "0"
            - name: TF_XLA_FLAGS
              value: '--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit'
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
{{- end }}
