apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appPrefix }}
spec:
  ports:
    - name: workers
      port: 5005
  selector:
    app: {{ .Values.appPrefix }}