{{- $image_version := "" }}
{{- $namespace := "" }}
{{- $appPrefix := "" }}
{{- $i := "" }}
{{- $current := "" }}
{{- $affinity := "" }}
{{- $resources := "" }}
{{- $myList := list }}
{{- $start := 1 }}
{{- $chief := "" }}
{{- $nproc_per_node := 1 }}

{{- $nproc_per_node := .Values.MultiWorkerMirroredStrategy.nproc_per_node | int  }}
{{- $image_version = printf "%s:%s" .Values.baseImage.repository .Values.baseImage.tag }}
{{- $namespace = .Release.Namespace | toString }}

{{- $appPrefix = .Values.appPrefix | toString }}
{{- $stop := .Values.MultiWorkerMirroredStrategy.replicas | int }}
{{- $chief = print $appPrefix "-chief-0-0" "." $appPrefix "-chief-0." $namespace ".svc.cluster.local:5005" | quote}}
{{- $myList = append $myList $chief }}

{{- with .Values.MultiWorkerMirroredStrategy.affinity }}
    {{- $affinity = toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.MultiWorkerMirroredStrategy.resources }}
    {{- $resources = toYaml . | nindent 12 }}
{{- end }}

{{- range untilStep $start $stop 1 }}
  {{- $i = . | toString }}
  {{- $current = print $appPrefix "-worker-" $i "-0." $appPrefix "-worker-" $i "." $namespace ".svc.cluster.local:5005" | quote }}
  {{- $myList = append $myList $current }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appPrefix }}-chief-0"
  labels:
    app: {{ $appPrefix }}
    worker: "{{ .Values.appPrefix }}-chief-0"
spec:
  ports:
    - name: workers
      port: 5005
  selector:
    worker: "{{ .Values.appPrefix }}-chief-0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.appPrefix }}-chief-0"
  labels:
    app: {{ .Values.appPrefix }}
spec:
  serviceName: "{{ .Values.appPrefix }}-chief-0"
  replicas: 1
  selector:
    matchLabels:
      worker: "{{ .Values.appPrefix }}-chief-0"
  template:
    metadata:
      labels: 
        app: {{ .Values.appPrefix }}
        worker: "{{ .Values.appPrefix }}-chief-0"
    spec:
    {{- with .Values.MultiWorkerMirroredStrategy.affinity }}
      affinity: 
        {{- toYaml . | nindent 12 }}
    {{- end }}
      imagePullSecrets:
        - name: ngc-secret
      containers:
        - name: "{{ .Values.appPrefix }}-chief-0"
          image: "{{ .Values.baseImage.repository }}:{{ .Values.baseImage.tag }}"
          imagePullPolicy: {{ .Values.baseImage.pullPolicy }}
        {{- with .Values.MultiWorkerMirroredStrategy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          ports:
            - name: workers
              containerPort: 5005 
          args:
          - sleep
          - infinity
          env:
            - name: TF_CONFIG
              value: '{"cluster": {"worker": [{{ join "," $myList }}]}, "task": {"index": 0, "type": "worker"}}'
            - name: APP_NAME
              value: "{{ .Values.appPrefix }}"
            - name: NUM_GPUS
              value: "{{ $nproc_per_node }}"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
