appPrefix: pytorch-distributed

MultiprocessingDistributed:
  replicas: 3
  nproc_per_node: 1
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: In
                values:
                  - "1"
                  - "2"
                  - "4"
                  - "8"
                  - "16"
  args:
    - python
    - train.py
    - --model=resnet18
    - --batch-size=1024
    - --epochs=10
    - --lr=0.5
    - --momentum=0.9
    - --weight-decay=0.00002
    - --lr-step-size=30
    - --lr-gamma=0.1
    - --print-freq=1
    - --val-resize-size=28 
    - --val-crop-size=28 
    - --train-crop-size=28
    - --output-dir=/workspace/data/resnet18
    - --amp

imageCredentials:
  registry: nvcr.io
  username: $oauthtoken
  password: "api-key"
  email: "user@nvidia.com"

baseImage:
  repository: registry.local:31500/distributed/pytorch
  pullPolicy: Always
  tag: "v0.1.0"
  imagePullSecrets:
    - ngc-secret
