appPrefix: pytorch-distributed

MultiprocessingDistributed:
  replicas: 3
  nproc_per_node: 1
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: In
                values:
                  - "1"
                  - "2"
                  - "4"
                  - "8"
                  - "16"
  args:
    - python
    - -m
    - torch.distributed.launch
    - --use_env
    - ./main.py
    - /imagenet
    - --training-only
    - --data-backend=syntetic
    - --epochs=10
    - --prof=70
    - --batch-size=256
    - --learning-rate=0.1
    - --arch=resnet50
    - --workspace=/workspace/rn50
    - --num-classes=10
    - --image-size=28
    - --amp
    - --static-loss-scale=128

imageCredentials:
  registry: nvcr.io
  username: $oauthtoken
  password: "api-key"
  email: "user@nvidia.com"

baseImage:
  repository: registry.local:31500/distributed/pytorch
  pullPolicy: Always
  tag: "v0.1.0"
  imagePullSecrets:
    - ngc-secret
