appPrefix: tensorflow-distributed

MultiWorkerMirroredStrategy:
  replicas: 3
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: In
                values:
                  - "1"
                  - "2"
                  - "4"
                  - "8"

service:
  nodePort: 30600

imageCredentials:
  registry: nvcr.io
  username: $oauthtoken
  password: "api-key"
  email: "user@nvidia.com"

baseImage:
  repository: nvcr.io/nvidia/tensorflow
  pullPolicy: IfNotPresent
  tag: "22.01-tf2-py3"
  imagePullSecrets:
    - ngc-secret
 
persistentVolume:
  storage: 64Gi