{{- if .Values.createCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: container-secret
  labels:
    app: {{ .Values.appPrefix }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}