---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appPrefix }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ports:
    - name: workers
      port: 5005
  clusterIP: None
  selector:
    app: {{ .Values.appPrefix }}