apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appPrefix }}-pv
  labels:
    app: {{ .Values.appPrefix }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.appPrefix }}-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}