apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-tensorboard
  labels:
    app: {{ .Values.appPrefix }}
spec:
  type: NodePort
  ports:
    - name: tensorboard
      nodePort: {{ .Values.service.nodePort }}
      port: 6006
      protocol: TCP
      targetPort: 6006
  selector:
    app: {{ .Values.appPrefix }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-subdomain
  labels:
    app: {{ .Values.appPrefix }}
spec:
  clusterIP: None
  ports:
    - name: workers
      port: 5005
      protocol: TCP
      targetPort: 5005
  selector:
    name: {{ .Values.appPrefix }}-workers
