apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-tensorboard
  labels:
    app: {{ .Values.appPrefix }}
spec:
  type: NodePort
  ports:
    - name: tensorboard
      nodePort: {{ .Values.service.nodePort }}
      port: 6006
      protocol: TCP
      targetPort: 6006
  selector:
    app: {{ .Values.appPrefix }}-tensorboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}
  labels:
    app: {{ .Values.appPrefix }}
spec:
  ports:
    - name: workers
      port: 5005
    - name: profiler-port
      port: 2223
    - name: web
      port: 80
  clusterIP: None
  selector:
    app: {{ .Values.appPrefix }}
