{{- $image_version := "" }}
{{- $namespace := "" }}
{{- $appPrefix := "" }}
{{- $i := "" }}
{{- $current := "" }}
{{- $affinity := "" }}
{{- $resources := "" }}
{{- $myList := list }}
{{- $start := 1 }}
{{- $chief := "" }}

{{- $image_version = printf "%s:%s" .Values.baseImage.repository .Values.baseImage.tag }}
{{- $namespace = .Release.Namespace | toString }}

{{- $appPrefix = .Values.appPrefix | toString }}
{{- $stop := .Values.MultiWorkerMirroredStrategy.replicas | int }}
{{- $chief = print $appPrefix "-chief-0-0" "." $appPrefix "." $namespace ".svc.cluster.local:5005" | quote}}
{{- $myList = append $myList $chief }}

{{- with .Values.MultiWorkerMirroredStrategy.affinity }}
    {{- $affinity = toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.MultiWorkerMirroredStrategy.resources }}
    {{- $resources = toYaml . | nindent 12 }}
{{- end }}

{{- range untilStep $start $stop 1 }}
  {{- $i = . | toString }}
  {{- $current = print $appPrefix "-worker-" $i "-0." $appPrefix "." $namespace ".svc.cluster.local:5005" | quote }}
  {{- $myList = append $myList $current }}
{{- end }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.appPrefix }}-chief-0"
  labels:
    app: {{ .Values.appPrefix }}
spec:
  serviceName: {{ .Values.appPrefix }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appPrefix }}
  template:
    metadata:
      labels: 
        app: {{ .Values.appPrefix }}
    spec:
    {{- with .Values.MultiWorkerMirroredStrategy.affinity }}
      affinity: 
        {{- toYaml . | nindent 12 }}
    {{- end }}
      imagePullSecrets:
        - name: ngc-secret
      containers:
        - name: "{{ .Values.appPrefix }}-chief-0"
          image: "{{ .Values.baseImage.repository }}:{{ .Values.baseImage.tag }}"
          imagePullPolicy: {{ .Values.baseImage.pullPolicy }}
        {{- with .Values.MultiWorkerMirroredStrategy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          ports:
            - name: workers
              containerPort: 5005 
          command: [ "sh", "-c"]
          args:
          - python3 worker.py
          env:
            - name: TF_CONFIG
              value: '{"cluster": {"worker": [{{ join "," $myList }}]}, "task": {"index": 0, "type": "worker"}}'
            - name: APP_NAME
              value: "{{ .Values.appPrefix }}"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: {{ .Values.appPrefix }}-storage
              mountPath: /workspace
      initContainers:
        - name: {{ .Values.appPrefix }}-init
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.appPrefix }}-worker-{{ sub .Values.MultiWorkerMirroredStrategy.replicas 1 }}-0.{{ .Values.appPrefix }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for all workers server instance.; sleep 5; done']
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: {{ .Values.appPrefix }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appPrefix }}-pvc
